title:            Leo's Portfolio
description:      Open source software engineer
logo:             icon.jpg
disqus_shortname:
#Comment out url when working locally to resolve base urls correctly
url:              http://leoj.js.org

# Owner/author information
owner:
  name:           Leo Hsieh
  avatar:         profile.jpeg
  email:          leo0924@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Leohsieh0924
  facebook:
  github:         LeoAJ
  stackexchange:
  linkedin:       leohsieh
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/107983723272310465160/

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Personal Projects
    url: /personalProjects
  - title: Publications
    url: /publications
  - title: Certification
    url: /certification
  - title: Contact
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
highlighter:    rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]
